site_name: IT-Viden
nav:
   - Home: index.md
   - About: about.md
   - ...
theme:
  name: material
  palette:
    # Force dark mode as default
    - scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to light

plugins:
  - search
  - awesome-pages
  - copybutton
# awesome-pages autogenerer navigation
