site_name: IT-Viden

nav:
  - Home: index.md
  - About: about.md
  - ...

theme:
  name: material
  features:
    - content.code.copy        # Adds "Copy" button to code blocks
    - content.code.select      # Adds "Select all" button to code blocks
  palette:
    # Dark mode is default, but toggle is available
    - scheme: default
      primary: indigo
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode

plugins:
  - search
  - awesome-pages  # Autogenerates navigation from .pages files

extra_css:
  - https://cdn.datatables.net/2.0.7/css/dataTables.dataTables.min.css

extra_javascript:
  - https://code.jquery.com/jquery-3.7.1.min.js
  - https://cdn.datatables.net/2.0.7/js/jquery.dataTables.min.js
  - javascripts/datatables-init.js

  
markdown_extensions:
  - attr_list # This is the crucial extension
